"""empty message

Revision ID: 87b5959ca7e6
Revises: bc5126d31b2d
Create Date: 2016-11-09 18:06:43.551125

"""

# revision identifiers, used by Alembic.
revision = '87b5959ca7e6'
down_revision = 'bc5126d31b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('taste_profile', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'taste_profile')
    ### end Alembic commands ###
