"""empty message

Revision ID: bc5126d31b2d
Revises: None
Create Date: 2016-10-28 03:58:29.004144

"""

# revision identifiers, used by Alembic.
revision = 'bc5126d31b2d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beer_name', sa.String(length=80), nullable=False),
    sa.Column('abv', sa.Numeric(), nullable=False),
    sa.Column('bitter', sa.Numeric(), nullable=False),
    sa.Column('color', sa.Numeric(), nullable=False),
    sa.Column('fruit', sa.Numeric(), nullable=False),
    sa.Column('hoppy', sa.Numeric(), nullable=False),
    sa.Column('malty', sa.Numeric(), nullable=False),
    sa.Column('roasty', sa.Numeric(), nullable=False),
    sa.Column('smoke', sa.Numeric(), nullable=False),
    sa.Column('sour', sa.Numeric(), nullable=False),
    sa.Column('spice', sa.Numeric(), nullable=False),
    sa.Column('sweet', sa.Numeric(), nullable=False),
    sa.Column('wood', sa.Numeric(), nullable=False),
    sa.Column('family', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beer_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'beer_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('rating')
    op.drop_table('users')
    op.drop_table('beers')
    ### end Alembic commands ###
